version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app  # Mount the local api directory to the /app directory in the container
    environment:
      - NODE_ENV=development  

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "5173:80"
    depends_on:
      - api  
    volumes:
      - ./web:/app  
    environment:
      - NODE_ENV=development 
